language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update

install:
  - composer install -n

script:
  - vendor/bin/phpunit
